Algoritmo "semnome"

Var

   x, y: real

Inicio

   escreval("Digite dois numeros:")
   leia(x)
   leia(y)
   
   enquanto x <> y faca
      se x < y entao
         escreval("Crescente")
      fimse
      
      se x > y entao
         escreval("Decrescente")
      fimse
      
      escreva("Digite outros dois numeros:" )
      leia(x)
      leia(y)


      
   fimenquanto
   
   



Fimalgoritmo